### ISSUE TITLE
[Recommendation] Amplify text that says not to use Windows PowerShell in section 3 (Deploy to Azure) 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-learncloud#1]
Depending on how important it is to use Powershell vs. Windows Powershell, I'd recommend bolding the "Please use Powershell and not Windows Powershell." or doing something to make it stand out more. I completely missed it despite "reading" through it a few times. 

![image](https://github.com/microsoft/vscode-learncloud/assets/19276747/21c98646-ac8e-425d-a3f1-6f919c8eb836)

**Comment by BandaruDheeraj** [comment]
Fixed
